// filename: eventloop.js
// Code Generated by Sidekick is for learning and experimentation purposes only.
console.log('1 - start')

setTimeout(() => console.log('2 - setTimeout'), 0)

setImmediate(() => console.log('3 - setImmediate'))

Promise.resolve().then(() => console.log('4 - Promise.then'))

process.nextTick(() => console.log('5 - nextTick'))

console.log('6 - end')
